[2025-10-31T23:04:04.348+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:04:04.364+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: absa_streaming_lifecycle_full.deploy_producer scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:04:04.368+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: absa_streaming_lifecycle_full.deploy_producer scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:04:04.368+0700] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2025-10-31T23:04:04.374+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): deploy_producer> on 2025-10-31 15:00:00+00:00
[2025-10-31T23:04:04.380+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2068) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:04:04.381+0700] {standard_task_runner.py:63} INFO - Started process 2077 to run task
[2025-10-31T23:04:04.383+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'absa_streaming_lifecycle_full', 'deploy_producer', 'scheduled__2025-10-31T15:00:00+00:00', '--job-id', '423', '--raw', '--subdir', 'DAGS_FOLDER/absa_streaming_lifecycle_full.py', '--cfg-path', '/tmp/tmpmek4l_zi']
[2025-10-31T23:04:04.386+0700] {standard_task_runner.py:91} INFO - Job 423: Subtask deploy_producer
[2025-10-31T23:04:04.431+0700] {task_command.py:426} INFO - Running <TaskInstance: absa_streaming_lifecycle_full.deploy_producer scheduled__2025-10-31T15:00:00+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:04:04.488+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='absa_streaming_lifecycle_full' AIRFLOW_CTX_TASK_ID='deploy_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T15:00:00+00:00'
[2025-10-31T23:04:04.489+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:04:04.490+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:04:04.490+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/absa_streaming/scripts/run_producer.sh"']
[2025-10-31T23:04:04.502+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:04:04.511+0700] {subprocess.py:93} INFO - [Producer] Starting Kafka Producer...
[2025-10-31T23:04:04.533+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T23:04:04.533+0700] {subprocess.py:93} INFO -   File "/opt/***/projects/absa_streaming/scripts/producer.py", line 10, in <module>
[2025-10-31T23:04:04.533+0700] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-10-31T23:04:04.533+0700] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-10-31T23:04:04.536+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:04:04.537+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:04:04.547+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:04:04.550+0700] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=absa_streaming_lifecycle_full, task_id=deploy_producer, execution_date=20251031T150000, start_date=20251031T160404, end_date=20251031T160404
[2025-10-31T23:04:04.558+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 423 for task deploy_producer (Bash command failed. The command returned a non-zero exit code 1.; 2077)
[2025-10-31T23:04:04.595+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:04:04.614+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:04:04.617+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-10-31T23:24:30.605+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:24:30.620+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: absa_streaming_lifecycle_full.deploy_producer scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:24:30.623+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: absa_streaming_lifecycle_full.deploy_producer scheduled__2025-10-31T15:00:00+00:00 [queued]>
[2025-10-31T23:24:30.624+0700] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2025-10-31T23:24:30.629+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): deploy_producer> on 2025-10-31 15:00:00+00:00
[2025-10-31T23:24:30.635+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3539) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:24:30.637+0700] {standard_task_runner.py:63} INFO - Started process 3541 to run task
[2025-10-31T23:24:30.638+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'absa_streaming_lifecycle_full', 'deploy_producer', 'scheduled__2025-10-31T15:00:00+00:00', '--job-id', '469', '--raw', '--subdir', 'DAGS_FOLDER/absa_streaming_lifecycle_full.py', '--cfg-path', '/tmp/tmpw7270s7f']
[2025-10-31T23:24:30.641+0700] {standard_task_runner.py:91} INFO - Job 469: Subtask deploy_producer
[2025-10-31T23:24:30.681+0700] {task_command.py:426} INFO - Running <TaskInstance: absa_streaming_lifecycle_full.deploy_producer scheduled__2025-10-31T15:00:00+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:24:30.744+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='absa_streaming_lifecycle_full' AIRFLOW_CTX_TASK_ID='deploy_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T15:00:00+00:00'
[2025-10-31T23:24:30.745+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:24:30.746+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:24:30.747+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/absa_streaming/scripts/run_producer.sh"']
[2025-10-31T23:24:30.758+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:24:30.767+0700] {subprocess.py:93} INFO - [Producer] Starting Kafka Producer...
[2025-10-31T23:24:30.920+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T23:24:30.921+0700] {subprocess.py:93} INFO -   File "/opt/***/projects/absa_streaming/scripts/producer.py", line 10, in <module>
[2025-10-31T23:24:30.921+0700] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-10-31T23:24:30.921+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/__init__.py", line 23, in <module>
[2025-10-31T23:24:30.921+0700] {subprocess.py:93} INFO -     from kafka.consumer import KafkaConsumer
[2025-10-31T23:24:30.922+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/consumer/__init__.py", line 3, in <module>
[2025-10-31T23:24:30.922+0700] {subprocess.py:93} INFO -     from kafka.consumer.group import KafkaConsumer
[2025-10-31T23:24:30.922+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/consumer/group.py", line 13, in <module>
[2025-10-31T23:24:30.922+0700] {subprocess.py:93} INFO -     from kafka.consumer.fetcher import Fetcher
[2025-10-31T23:24:30.922+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/consumer/fetcher.py", line 19, in <module>
[2025-10-31T23:24:30.922+0700] {subprocess.py:93} INFO -     from kafka.record import MemoryRecords
[2025-10-31T23:24:30.923+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/record/__init__.py", line 1, in <module>
[2025-10-31T23:24:30.923+0700] {subprocess.py:93} INFO -     from kafka.record.memory_records import MemoryRecords, MemoryRecordsBuilder
[2025-10-31T23:24:30.923+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/record/memory_records.py", line 27, in <module>
[2025-10-31T23:24:30.923+0700] {subprocess.py:93} INFO -     from kafka.record.legacy_records import LegacyRecordBatch, LegacyRecordBatchBuilder
[2025-10-31T23:24:30.923+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/record/legacy_records.py", line 50, in <module>
[2025-10-31T23:24:30.923+0700] {subprocess.py:93} INFO -     from kafka.codec import (
[2025-10-31T23:24:30.924+0700] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/codec.py", line 9, in <module>
[2025-10-31T23:24:30.924+0700] {subprocess.py:93} INFO -     from kafka.vendor.six.moves import range
[2025-10-31T23:24:30.924+0700] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka.vendor.six.moves'
[2025-10-31T23:24:30.931+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:24:30.932+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:24:30.942+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:24:30.944+0700] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=absa_streaming_lifecycle_full, task_id=deploy_producer, execution_date=20251031T150000, start_date=20251031T162430, end_date=20251031T162430
[2025-10-31T23:24:30.953+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 469 for task deploy_producer (Bash command failed. The command returned a non-zero exit code 1.; 3541)
[2025-10-31T23:24:30.973+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:24:30.992+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:24:30.994+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
