[2025-10-31T23:20:34.303+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T23:20:34.321+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: absa_streaming_lifecycle_full.deploy_consumer manual__2025-10-31T16:20:33.309051+00:00 [queued]>
[2025-10-31T23:20:34.327+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: absa_streaming_lifecycle_full.deploy_consumer manual__2025-10-31T16:20:33.309051+00:00 [queued]>
[2025-10-31T23:20:34.327+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-10-31T23:20:34.335+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): deploy_consumer> on 2025-10-31 16:20:33.309051+00:00
[2025-10-31T23:20:34.340+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2630) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T23:20:34.341+0700] {standard_task_runner.py:63} INFO - Started process 2639 to run task
[2025-10-31T23:20:34.342+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'absa_streaming_lifecycle_full', 'deploy_consumer', 'manual__2025-10-31T16:20:33.309051+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/absa_streaming_lifecycle_full.py', '--cfg-path', '/tmp/tmpgqbavd5u']
[2025-10-31T23:20:34.345+0700] {standard_task_runner.py:91} INFO - Job 447: Subtask deploy_consumer
[2025-10-31T23:20:34.395+0700] {task_command.py:426} INFO - Running <TaskInstance: absa_streaming_lifecycle_full.deploy_consumer manual__2025-10-31T16:20:33.309051+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T23:20:34.460+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='absa_streaming_lifecycle_full' AIRFLOW_CTX_TASK_ID='deploy_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T16:20:33.309051+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T16:20:33.309051+00:00'
[2025-10-31T23:20:34.462+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T23:20:34.463+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:20:34.463+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/absa_streaming/scripts/run_consumer.sh"']
[2025-10-31T23:20:34.482+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T23:20:34.493+0700] {subprocess.py:93} INFO - [Consumer] Starting Spark Structured Streaming job...
[2025-10-31T23:20:34.532+0700] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-10-31T23:20:35.389+0700] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.12/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-10-31T23:20:35.432+0700] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-10-31T23:20:35.432+0700] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-10-31T23:20:35.434+0700] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-10-31T23:20:35.434+0700] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2025-10-31T23:20:35.434+0700] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-b9020264-886c-4b56-bab0-096d3f94538e;1.0
[2025-10-31T23:20:35.435+0700] {subprocess.py:93} INFO - 	confs: [default]
[2025-10-31T23:20:35.597+0700] {subprocess.py:93} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.1 in central
[2025-10-31T23:20:35.653+0700] {subprocess.py:93} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.1 in central
[2025-10-31T23:20:36.107+0700] {subprocess.py:93} INFO - 	found org.apache.kafka#kafka-clients;3.4.1 in central
[2025-10-31T23:20:36.307+0700] {subprocess.py:93} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2025-10-31T23:20:36.624+0700] {subprocess.py:93} INFO - 	found org.xerial.snappy#snappy-java;1.1.10.3 in central
[2025-10-31T23:20:38.174+0700] {subprocess.py:93} INFO - 	found org.slf4j#slf4j-api;2.0.7 in central
[2025-10-31T23:20:42.631+0700] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-10-31T23:20:42.798+0700] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-10-31T23:20:45.282+0700] {subprocess.py:93} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-10-31T23:20:45.287+0700] {subprocess.py:93} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-10-31T23:20:45.292+0700] {subprocess.py:93} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-10-31T23:20:45.296+0700] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.6.0 in central
[2025-10-31T23:20:45.299+0700] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.31.0 in central
[2025-10-31T23:20:45.382+0700] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.1/spark-token-provider-kafka-0-10_2.12-3.5.1.jar ...
[2025-10-31T23:20:45.462+0700] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.1!spark-token-provider-kafka-0-10_2.12.jar (159ms)
[2025-10-31T23:20:45.552+0700] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar ...
[2025-10-31T23:20:46.131+0700] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
[2025-10-31T23:20:46.208+0700] {subprocess.py:93} INFO - 	[SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (163ms)
[2025-10-31T23:20:46.275+0700] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar ...
[2025-10-31T23:20:46.346+0700] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.commons#commons-pool2;2.11.1!commons-pool2.jar (137ms)
[2025-10-31T23:20:46.429+0700] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.4/hadoop-client-runtime-3.3.4.jar ...
[2025-10-31T23:20:48.066+0700] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.hadoop#hadoop-client-runtime;3.3.4!hadoop-client-runtime.jar (1720ms)
[2025-10-31T23:20:48.132+0700] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.4/hadoop-client-api-3.3.4.jar ...
[2025-10-31T23:20:49.365+0700] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.hadoop#hadoop-client-api;3.3.4!hadoop-client-api.jar (1298ms)
[2025-10-31T23:20:49.440+0700] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
[2025-10-31T23:20:49.530+0700] {subprocess.py:93} INFO - 	[SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (164ms)
[2025-10-31T23:20:49.531+0700] {subprocess.py:93} INFO - :: resolution report :: resolve 9868ms :: artifacts dl 4229ms
[2025-10-31T23:20:49.531+0700] {subprocess.py:93} INFO - 	:: modules in use:
[2025-10-31T23:20:49.532+0700] {subprocess.py:93} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-10-31T23:20:49.532+0700] {subprocess.py:93} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-10-31T23:20:49.532+0700] {subprocess.py:93} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-10-31T23:20:49.532+0700] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
[2025-10-31T23:20:49.533+0700] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
[2025-10-31T23:20:49.533+0700] {subprocess.py:93} INFO - 	org.apache.kafka#kafka-clients;3.4.1 from central in [default]
[2025-10-31T23:20:49.533+0700] {subprocess.py:93} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.1 from central in [default]
[2025-10-31T23:20:49.534+0700] {subprocess.py:93} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.1 from central in [default]
[2025-10-31T23:20:49.534+0700] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.31.0 from central in [default]
[2025-10-31T23:20:49.534+0700] {subprocess.py:93} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2025-10-31T23:20:49.535+0700] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.6.0 from central in [default]
[2025-10-31T23:20:49.535+0700] {subprocess.py:93} INFO - 	org.slf4j#slf4j-api;2.0.7 from central in [default]
[2025-10-31T23:20:49.535+0700] {subprocess.py:93} INFO - 	org.xerial.snappy#snappy-java;1.1.10.3 from central in [default]
[2025-10-31T23:20:49.535+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-10-31T23:20:49.535+0700] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-10-31T23:20:49.535+0700] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-10-31T23:20:49.536+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-10-31T23:20:49.536+0700] {subprocess.py:93} INFO - 	|      default     |   13  |   7   |   6   |   0   ||   13  |   6   |
[2025-10-31T23:20:49.536+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-10-31T23:20:49.536+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.536+0700] {subprocess.py:93} INFO - :: problems summary ::
[2025-10-31T23:20:49.537+0700] {subprocess.py:93} INFO - :::: WARNINGS
[2025-10-31T23:20:49.537+0700] {subprocess.py:93} INFO - 		[FAILED     ] org.apache.kafka#kafka-clients;3.4.1!kafka-clients.jar: Downloaded file size (0) doesn't match expected Content Length (5050443) for https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar. Please retry. (582ms)
[2025-10-31T23:20:49.537+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.537+0700] {subprocess.py:93} INFO - 		[FAILED     ] org.apache.kafka#kafka-clients;3.4.1!kafka-clients.jar: Downloaded file size (0) doesn't match expected Content Length (5050443) for https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar. Please retry. (582ms)
[2025-10-31T23:20:49.538+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.538+0700] {subprocess.py:93} INFO - 	==== central: tried
[2025-10-31T23:20:49.538+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.538+0700] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar
[2025-10-31T23:20:49.538+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.538+0700] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-10-31T23:20:49.538+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.539+0700] {subprocess.py:93} INFO - 		::              FAILED DOWNLOADS            ::
[2025-10-31T23:20:49.539+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.539+0700] {subprocess.py:93} INFO - 		:: ^ see resolution messages for details  ^ ::
[2025-10-31T23:20:49.539+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.539+0700] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-10-31T23:20:49.539+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.540+0700] {subprocess.py:93} INFO - 		:: org.apache.kafka#kafka-clients;3.4.1!kafka-clients.jar
[2025-10-31T23:20:49.540+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.540+0700] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-10-31T23:20:49.540+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.540+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.540+0700] {subprocess.py:93} INFO - 
[2025-10-31T23:20:49.540+0700] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-10-31T23:20:49.540+0700] {subprocess.py:93} INFO - Exception in thread "main" java.lang.RuntimeException: [download failed: org.apache.kafka#kafka-clients;3.4.1!kafka-clients.jar]
[2025-10-31T23:20:49.540+0700] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1608)
[2025-10-31T23:20:49.540+0700] {subprocess.py:93} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-10-31T23:20:49.541+0700] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:334)
[2025-10-31T23:20:49.541+0700] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2025-10-31T23:20:49.541+0700] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2025-10-31T23:20:49.541+0700] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2025-10-31T23:20:49.541+0700] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2025-10-31T23:20:49.541+0700] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2025-10-31T23:20:49.541+0700] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2025-10-31T23:20:49.541+0700] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-10-31T23:20:49.601+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:20:49.602+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T23:20:49.615+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:20:49.618+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=absa_streaming_lifecycle_full, task_id=deploy_consumer, execution_date=20251031T162033, start_date=20251031T162034, end_date=20251031T162049
[2025-10-31T23:20:49.626+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 447 for task deploy_consumer (Bash command failed. The command returned a non-zero exit code 1.; 2639)
[2025-10-31T23:20:49.642+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T23:20:49.661+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T23:20:49.662+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
