[2025-10-31T22:37:07.891+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T22:37:07.906+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: absa_streaming_lifecycle_full.deploy_consumer manual__2025-10-31T15:35:04.749162+00:00 [queued]>
[2025-10-31T22:37:07.909+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: absa_streaming_lifecycle_full.deploy_consumer manual__2025-10-31T15:35:04.749162+00:00 [queued]>
[2025-10-31T22:37:07.910+0700] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2025-10-31T22:37:07.915+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): deploy_consumer> on 2025-10-31 15:35:04.749162+00:00
[2025-10-31T22:37:07.921+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1187) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T22:37:07.922+0700] {standard_task_runner.py:63} INFO - Started process 1197 to run task
[2025-10-31T22:37:07.923+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'absa_streaming_lifecycle_full', 'deploy_consumer', 'manual__2025-10-31T15:35:04.749162+00:00', '--job-id', '327', '--raw', '--subdir', 'DAGS_FOLDER/absa_streaming_lifecycle_full.py', '--cfg-path', '/tmp/tmpogu0le8y']
[2025-10-31T22:37:07.926+0700] {standard_task_runner.py:91} INFO - Job 327: Subtask deploy_consumer
[2025-10-31T22:37:07.969+0700] {task_command.py:426} INFO - Running <TaskInstance: absa_streaming_lifecycle_full.deploy_consumer manual__2025-10-31T15:35:04.749162+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T22:37:08.038+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='absa_streaming_lifecycle_full' AIRFLOW_CTX_TASK_ID='deploy_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:35:04.749162+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T15:35:04.749162+00:00'
[2025-10-31T22:37:08.040+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T22:37:08.040+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T22:37:08.041+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/absa_streaming/scripts/run_consumer.sh"']
[2025-10-31T22:37:08.052+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T22:37:08.062+0700] {subprocess.py:93} INFO - [Consumer] Starting Spark Structured Streaming job...
[2025-10-31T22:37:08.063+0700] {subprocess.py:93} INFO - /opt/***/projects/absa_streaming/scripts/run_consumer.sh: line 15: spark-submit: command not found
[2025-10-31T22:37:08.064+0700] {subprocess.py:97} INFO - Command exited with return code 127
[2025-10-31T22:37:08.065+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T22:37:08.075+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-10-31T22:37:08.078+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=absa_streaming_lifecycle_full, task_id=deploy_consumer, execution_date=20251031T153504, start_date=20251031T153707, end_date=20251031T153708
[2025-10-31T22:37:08.085+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 327 for task deploy_consumer (Bash command failed. The command returned a non-zero exit code 127.; 1197)
[2025-10-31T22:37:08.136+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T22:37:08.153+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T22:37:08.153+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
