[2025-10-31T22:58:50.361+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T22:58:50.379+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: absa_streaming_lifecycle_full.deploy_producer scheduled__2025-10-31T14:00:00+00:00 [queued]>
[2025-10-31T22:58:50.383+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: absa_streaming_lifecycle_full.deploy_producer scheduled__2025-10-31T14:00:00+00:00 [queued]>
[2025-10-31T22:58:50.384+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-10-31T22:58:50.391+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): deploy_producer> on 2025-10-31 14:00:00+00:00
[2025-10-31T22:58:50.397+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1719) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T22:58:50.398+0700] {standard_task_runner.py:63} INFO - Started process 1723 to run task
[2025-10-31T22:58:50.400+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'absa_streaming_lifecycle_full', 'deploy_producer', 'scheduled__2025-10-31T14:00:00+00:00', '--job-id', '371', '--raw', '--subdir', 'DAGS_FOLDER/absa_streaming_lifecycle_full.py', '--cfg-path', '/tmp/tmp6oqyja6x']
[2025-10-31T22:58:50.402+0700] {standard_task_runner.py:91} INFO - Job 371: Subtask deploy_producer
[2025-10-31T22:58:50.475+0700] {task_command.py:426} INFO - Running <TaskInstance: absa_streaming_lifecycle_full.deploy_producer scheduled__2025-10-31T14:00:00+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T22:58:50.552+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='absa_streaming_lifecycle_full' AIRFLOW_CTX_TASK_ID='deploy_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T14:00:00+00:00'
[2025-10-31T22:58:50.553+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T22:58:50.554+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T22:58:50.554+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/absa_streaming/scripts/run_producer.sh"']
[2025-10-31T22:58:50.568+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T22:58:50.581+0700] {subprocess.py:93} INFO - [Producer] Starting Kafka Producer...
[2025-10-31T22:58:50.607+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-31T22:58:50.608+0700] {subprocess.py:93} INFO -   File "/opt/***/projects/absa_streaming/scripts/producer.py", line 10, in <module>
[2025-10-31T22:58:50.608+0700] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-10-31T22:58:50.608+0700] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-10-31T22:58:50.612+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T22:58:50.612+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T22:58:50.624+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T22:58:50.627+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=absa_streaming_lifecycle_full, task_id=deploy_producer, execution_date=20251031T140000, start_date=20251031T155850, end_date=20251031T155850
[2025-10-31T22:58:50.635+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 371 for task deploy_producer (Bash command failed. The command returned a non-zero exit code 1.; 1723)
[2025-10-31T22:58:50.656+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T22:58:50.676+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T22:58:50.677+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
