[2025-10-31T22:39:10.371+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-31T22:39:10.387+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: absa_streaming_lifecycle_full.deploy_consumer manual__2025-10-31T15:35:06.939039+00:00 [queued]>
[2025-10-31T22:39:10.390+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: absa_streaming_lifecycle_full.deploy_consumer manual__2025-10-31T15:35:06.939039+00:00 [queued]>
[2025-10-31T22:39:10.391+0700] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2025-10-31T22:39:10.396+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): deploy_consumer> on 2025-10-31 15:35:06.939039+00:00
[2025-10-31T22:39:10.401+0700] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1336) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-31T22:39:10.402+0700] {standard_task_runner.py:63} INFO - Started process 1342 to run task
[2025-10-31T22:39:10.404+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'absa_streaming_lifecycle_full', 'deploy_consumer', 'manual__2025-10-31T15:35:06.939039+00:00', '--job-id', '349', '--raw', '--subdir', 'DAGS_FOLDER/absa_streaming_lifecycle_full.py', '--cfg-path', '/tmp/tmpweuemjf6']
[2025-10-31T22:39:10.406+0700] {standard_task_runner.py:91} INFO - Job 349: Subtask deploy_consumer
[2025-10-31T22:39:10.446+0700] {task_command.py:426} INFO - Running <TaskInstance: absa_streaming_lifecycle_full.deploy_consumer manual__2025-10-31T15:35:06.939039+00:00 [running]> on host f7bb1ad77e89
[2025-10-31T22:39:10.501+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='absa_streaming_lifecycle_full' AIRFLOW_CTX_TASK_ID='deploy_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T15:35:06.939039+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T15:35:06.939039+00:00'
[2025-10-31T22:39:10.502+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-31T22:39:10.503+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T22:39:10.504+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "timeout 45m bash /opt/***/projects/absa_streaming/scripts/run_consumer.sh"']
[2025-10-31T22:39:10.516+0700] {subprocess.py:86} INFO - Output:
[2025-10-31T22:39:10.525+0700] {subprocess.py:93} INFO - [Consumer] Starting Spark Structured Streaming job...
[2025-10-31T22:39:10.526+0700] {subprocess.py:93} INFO - /opt/***/projects/absa_streaming/scripts/run_consumer.sh: line 15: spark-submit: command not found
[2025-10-31T22:39:10.527+0700] {subprocess.py:97} INFO - Command exited with return code 127
[2025-10-31T22:39:10.527+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-31T22:39:10.536+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-10-31T22:39:10.539+0700] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=absa_streaming_lifecycle_full, task_id=deploy_consumer, execution_date=20251031T153506, start_date=20251031T153910, end_date=20251031T153910
[2025-10-31T22:39:10.546+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 349 for task deploy_consumer (Bash command failed. The command returned a non-zero exit code 127.; 1342)
[2025-10-31T22:39:10.576+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-31T22:39:10.593+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T22:39:10.595+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
